name: R-cb2110 
channels: 
  - conda-forge
  - bioconda
  - defaults 
  - R 
dependencies: 
  - jupyter
  - r-base=4.3
  - r-tidyverse=2.0.0
  - r-dplyr=1.1.4
  - r-ggplot2=3.5.1
  - r-readxl=1.4.2
  - r-tidyr=1.3.1
  - r-viridis=0.6.5
  - r-parallelly=1.37.1
  - r-reticulate=1.37.0
  - r-stringr=1.5.1
  - r-quarto=1.4.4
  - r-visdat
  - r-naniar
 




# follow this vdo 
# https://www.youtube.com/watch?v=QI2Qg_1aySc
