---
title: "Lab 1"
format: 
  html:
    toc: true
    code-fold: true
    theme: lumen

jupyter:
    kernelspec:
        name: "ir43"
        language: "R"
        display_name: "R 4.3.2"
---

Welcome everyone to lab one. This worksheep will guide you to everything that you need including instructions, the questions and definitely the bonus questions for your extra scores. Before we start with anything, please fill in your information here so we can give you nice some nice scores later. 

- Member1:
- Member2: 
- Contact email: 

There will be ten questions and three bonus questions for you to answer. Please try to elaborate this exercise with the lectures from the first weeks on mass spectrometry. The goal of this lab is for you to enjoy mass spectrometry as it is a major technology in the field of proteomics. In other words, it is not that simple to understand it with in a few minutes but we are here to explore them all together. Nevertheless, we try to reduce several steps into just a simple exercise. 

## Intended learning outcomes (ILOs)

On completion of the lab, the student should be able to:

1. Demonstrate understandings and insights in mass spectrometry
2. Retrieve open access mass spectrometry data
3. Access organism proteome from database 
4. Identify the relevant issues of complexity in high-throughput data structure from mass spectrometry
5. Demonstrate capacity to store and handle high throughput data with efficiency 

## Let's start! 

In this lab, we will explore mass spectrometry proteomics database where we can find the data and explore them. There are many ways to do proteomics analysis but we will discuss based on the data that we see. One does not need to code here but we will explain how to do it together. 

<em>Let's begin by visiting [ProteomeCentral](https://proteomecentral.proteomexchange.org/), a central hub for searching mass spectrometry (MS) data repositories. Here, you can browse and access datasets from various proteomics resources such as PRIDE, PeptideAtlas, MassIVE, and more. That's because ProteomeCentral  belongs to [ProteomExchange](https://www.proteomexchange.org/) wihich is a centralized and standardized framework for all scientist working with proteomics mass spectrometry. Well, it does not keep the data itself. It just provides a link to where one can find the database and accession id easily. Of course, everything that one can see here is public. We are allowed to download and play with this data as we would like. Maybe at some point of your career time, one may publish MS data on ProteomExchange. 

Try making a simple search from there. One can pick several parameters of interests including type of samples and type of MS experiment of machine.</em>

## Q1. 
**Pick one dataset from there. What is there dataset identifier? Summarise the experiment in a short paragraph (<100 words). What do we expect to find from this MS dataset?** 

Ans.

## Q2.
**What samples were used and located in the organism/s in this experiment?**

Ans. 

## Q3. 
**What is the model of the instrument? What is its set-up for example DIA or DDA? Is it labelled or labelled-free quantification?**

Ans.

## Q4.
**Do we see the data according to the information on the submission or the article? What else are missing?** 

Ans. 

## Q5.
**Does it include SDRF file there? Why do we need SDRF file?**

Ans. 


## Q6. 
<em>Next step, peptide spectral matching (PSM) need a proteome to search against your experiment. Please just go to Uniprot.</em> **What proteome did you download from Uniprot? How many proteins are there?**

Ans. 

## Q7. 
**Does the number of proteins in the proteome impact the search? How? (Hint: Lukas's lecture)**

Ans. 

## Q8.
<em>At this step, you are able to do PSM. We can do it with a simple tool call [quantms](https://docs.quantms.org/latest/index.html). One can try running it with the tutorial [here](https://github.com/thanadol-git/quantms_example). It may take a few resources as MS data are always huge for any local computer</em> **Is there an alternative for quantms? How does the article work with PSM?**

Ans. 

## Q9. 
**Why do we need to add target decoys? How do they work?**

Ans. 

## Q10.
**What is the database containing adventitious proteins? Why are these proteins important?**

Ans. 

Hooray! Once you finish answering the questions, please render this markdown to pdf and upload it on Canvas.


## Bonus questions
### BQ1
***How does peptide identification step in [Q7.](## Q7.) work? ***  
Ans. 

### BQ2
**How can we run mass spectrometry experiments sustainably?**  
Ans. 

### BQ3. 
**Can we search with proteomes from more than one organism? How?**

Ans. 

- - -

## Edit
Generated: `r Sys.Date()`

## References
<em>https://pwilmart.github.io/blog/2020/09/19/shotgun-quantification-part2</em>